[package]
name = "busmap"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.12"
regex = "1"
tokio = { version = "1", features = ["full"] }